-- LINDA Config file for
-- Generated by LINDA Configurator


-- ############################################### --
-- ## EFIS block Mode 1
-- ############################################### --

-- EFIS block buttons and switches
EFIS1 = {
["ENABLED"]	= true  ,
["IDENT"]	= "Std"  ,
["INHG."] 	= Efis_INHG  ,
["HPA ."] 	= Efis_HPA  ,
["FD  ."] 	= Efis_FD_button  ,
["ILS ."] 	= Efis_ILS_button  ,
["CSTR."] 	= Efis_CSTR_button  ,
["WPT ."] 	= Efis_WPT_button  ,
["VORD."] 	= Efis_VORD_button  ,
["NDB ."] 	= Efis_NDB_button  ,
["ARPT."] 	= Efis_ARPT_button  ,
["VORL:"] 	= Efis_ADF1  ,
["VORR:"] 	= Efis_ADF2  ,
["VORL."] 	= Efis_VOR1  ,
["VORR."] 	= Efis_VOR2  ,
}


-- EFIS BARO knob
BARO1 = {
["A SHOW"]	= Altimeter_BARO_show  ,
["A  +"]	= Altimeter_BARO_plus  ,
["A ++"]	= Altimeter_BARO_plusfast  ,
["A  -"]	= Altimeter_BARO_minus  ,
["A --"]	= Altimeter_BARO_minusfast  ,
["PRESS"] 	= Altimeter_BARO_MODE_toggle  ,
["B SHOW"]	= empty  ,
["B  +"]	= empty  ,
["B ++"]	= empty  ,
["B  -"]	= empty  ,
["B --"]	= empty  ,
}


-- EFIS NDM knob
CTR1 = {
["A SHOW"]	= empty  ,
["A  +"]	= Efis_NDM_inc  ,
["A ++"]	= Efis_NDM_inc  ,
["A  -"]	= Efis_NDM_dec  ,
["A --"]	= Efis_NDM_dec  ,
["PRESS"] 	= empty  ,
["B SHOW"]	= empty  ,
["B  +"]	= empty  ,
["B ++"]	= empty  ,
["B  -"]	= empty  ,
["B --"]	= empty  ,
}


-- EFIS NDR knob
TFC1 = {
["A SHOW"]	= empty  ,
["A  +"]	= Efis_NDR_inc  ,
["A ++"]	= Efis_NDR_inc  ,
["A  -"]	= Efis_NDR_dec  ,
["A --"]	= Efis_NDR_dec  ,
["PRESS"] 	= empty  ,
["B SHOW"]	= empty  ,
["B  +"]	= empty  ,
["B ++"]	= empty  ,
["B  -"]	= empty  ,
["B --"]	= empty  ,
}


-- ############################################### --
-- ## EFIS block Mode 2
-- ############################################### --

-- EFIS block buttons and switches
EFIS2 = {
["ENABLED"]	= false  ,
["IDENT"]	= ""  ,
["INHG."] 	= empty  ,
["HPA ."] 	= empty  ,
["FD  ."] 	= empty  ,
["ILS ."] 	= empty  ,
["CSTR."] 	= empty  ,
["WPT ."] 	= empty  ,
["VORD."] 	= empty  ,
["NDB ."] 	= empty  ,
["ARPT."] 	= empty  ,
["VORL:"] 	= empty  ,
["VORR:"] 	= empty  ,
["VORL."] 	= empty  ,
["VORR."] 	= empty  ,
}


-- EFIS BARO knob
BARO2 = {
["A SHOW"]	= empty  ,
["A  +"]	= empty  ,
["A ++"]	= empty  ,
["A  -"]	= empty  ,
["A --"]	= empty  ,
["PRESS"] 	= empty  ,
["B SHOW"]	= empty  ,
["B  +"]	= empty  ,
["B ++"]	= empty  ,
["B  -"]	= empty  ,
["B --"]	= empty  ,
}


-- EFIS NDM knob
CTR2 = {
["A SHOW"]	= empty  ,
["A  +"]	= empty  ,
["A ++"]	= empty  ,
["A  -"]	= empty  ,
["A --"]	= empty  ,
["PRESS"] 	= empty  ,
["B SHOW"]	= empty  ,
["B  +"]	= empty  ,
["B ++"]	= empty  ,
["B  -"]	= empty  ,
["B --"]	= empty  ,
}


-- EFIS NDR knob
TFC2 = {
["A SHOW"]	= empty  ,
["A  +"]	= empty  ,
["A ++"]	= empty  ,
["A  -"]	= empty  ,
["A --"]	= empty  ,
["PRESS"] 	= empty  ,
["B SHOW"]	= empty  ,
["B  +"]	= empty  ,
["B ++"]	= empty  ,
["B  -"]	= empty  ,
["B --"]	= empty  ,
}


-- ############################################### --
-- ## EFIS block Mode 3
-- ############################################### --

-- EFIS block buttons and switches
EFIS3 = {
["ENABLED"]	= false  ,
["IDENT"]	= ""  ,
["INHG."] 	= empty  ,
["HPA ."] 	= empty  ,
["FD  ."] 	= empty  ,
["ILS ."] 	= empty  ,
["CSTR."] 	= empty  ,
["WPT ."] 	= empty  ,
["VORD."] 	= empty  ,
["NDB ."] 	= empty  ,
["ARPT."] 	= empty  ,
["VORL:"] 	= empty  ,
["VORR:"] 	= empty  ,
["VORL."] 	= empty  ,
["VORR."] 	= empty  ,
}


-- EFIS BARO knob
BARO3 = {
["A SHOW"]	= empty  ,
["A  +"]	= empty  ,
["A ++"]	= empty  ,
["A  -"]	= empty  ,
["A --"]	= empty  ,
["PRESS"] 	= empty  ,
["B SHOW"]	= empty  ,
["B  +"]	= empty  ,
["B ++"]	= empty  ,
["B  -"]	= empty  ,
["B --"]	= empty  ,
}


-- EFIS NDM knob
CTR3 = {
["A SHOW"]	= empty  ,
["A  +"]	= empty  ,
["A ++"]	= empty  ,
["A  -"]	= empty  ,
["A --"]	= empty  ,
["PRESS"] 	= empty  ,
["B SHOW"]	= empty  ,
["B  +"]	= empty  ,
["B ++"]	= empty  ,
["B  -"]	= empty  ,
["B --"]	= empty  ,
}


-- EFIS NDR knob
TFC3 = {
["A SHOW"]	= empty  ,
["A  +"]	= empty  ,
["A ++"]	= empty  ,
["A  -"]	= empty  ,
["A --"]	= empty  ,
["PRESS"] 	= empty  ,
["B SHOW"]	= empty  ,
["B  +"]	= empty  ,
["B ++"]	= empty  ,
["B  -"]	= empty  ,
["B --"]	= empty  ,
}


-- ############################################### --
-- ## MCP block Mode 1
-- ############################################### --

-- MCP block buttons and switches
MCP1 = {
["ENABLED"]	= true  ,
["IDENT"] 	= "MCP1"  ,
["MACH."] 	= Autopilot_MACH_button  ,
["LOC ."] 	= Autopilot_LOC_button  ,
["TRK ."] 	= Autopilot_TRK_button  ,
["AP1 ."] 	= Autopilot_AP1_button  ,
["AP2."] 	= Autopilot_AP2_button  ,
["ATHR."] 	= Autopilot_ATHR_button  ,
["EXPD."] 	= Autopilot_EXPD_button  ,
["MTR ."] 	= Autopilot_MTR_button  ,
["APPR."] 	= Autopilot_APPR_button  ,
}


-- MCP SPD knob
SPD1 = {
["A SHOW"]	= SPD_show  ,
["A  +"]	= SPD_plus  ,
["A ++"]	= SPD_plusfast  ,
["A  -"]	= SPD_minus  ,
["A --"]	= SPD_minusfast  ,
["PRESS"] 	= SPD_press  ,
["PULL"]        = SPD_pull ,
}


-- MCP HDG knob
HDG1 = {
["A SHOW"]	= HDG_show  ,
["A  +"]	= HDG_plus  ,
["A ++"]	= HDG_plusfast  ,
["A  -"]	= HDG_minus  ,
["A --"]	= HDG_minusfast  ,
["PRESS"] 	= HDG_press  ,
["PULL"]        = HDG_pull ,
}


-- MCP ALT knob
ALT1 = {
["A SHOW"]	= ALT_show  ,
["A  +"]	= ALT_plus  ,
["A ++"]	= ALT_plusfast  ,
["A  -"]	= ALT_minus  ,
["A --"]	= ALT_minusfast  ,
["PRESS"] 	= ALT_press  ,
["PULL"]        = ALT_pull ,
}


-- MCP VVS knob
VVS1 = {
["A SHOW"]	= VVS_show  ,
["A  +"]	= VVS_plus  ,
["A ++"]	= VVS_plusfast  ,
["A  -"]	= VVS_minus  ,
["A --"]	= VVS_minusfast  ,
["PRESS"] 	= VVS_press  ,
["PULL"]        = VVS_pull ,
}


-- ############################################### --
-- ## MCP block Mode 2
-- ############################################### --

-- MCP block buttons and switches
MCP2 = {
["ENABLED"]	= false  ,
["IDENT"] 	= "MCP2"  ,
["MACH."] 	= Autopilot_MACH_button  ,
["LOC ."] 	= Autopilot_LOC_button  ,
["TRK ."] 	= Autopilot_TRK_button  ,
["AP1 ."] 	= Autopilot_AP1_button  ,
["AP2."] 	= Autopilot_AP2_button  ,
["ATHR."] 	= Autopilot_ATHR_button  ,
["EXPD."] 	= Autopilot_EXPD_button  ,
["MTR ."] 	= Autopilot_MTR_button  ,
["APPR."] 	= Autopilot_APPR_button  ,
}


-- MCP SPD knob
SPD2 = {
["A SHOW"]	= SPD_show  ,
["A  +"]	= SPD_plus  ,
["A ++"]	= SPD_plusfast  ,
["A  -"]	= SPD_minus  ,
["A --"]	= SPD_minusfast  ,
["PRESS"] 	= SPD_press  ,
["PULL"]        = SPD_pull ,
}


-- MCP HDG knob
HDG2 = {
["A SHOW"]	= HDG_show  ,
["A  +"]	= HDG_plus  ,
["A ++"]	= HDG_plusfast  ,
["A  -"]	= HDG_minus  ,
["A --"]	= HDG_minusfast  ,
["PRESS"] 	= HDG_press  ,
["PULL"]        = HDG_pull ,
}


-- MCP ALT knob
ALT2 = {
["A SHOW"]	= ALT_show  ,
["A  +"]	= ALT_plus  ,
["A ++"]	= ALT_plusfast  ,
["A  -"]	= ALT_minus  ,
["A --"]	= ALT_minusfast  ,
["PRESS"] 	= ALT_press  ,
["PULL"]        = ALT_pull ,
}


-- MCP VVS knob
VVS2 = {
["A SHOW"]	= VVS_show  ,
["A  +"]	= VVS_plus  ,
["A ++"]	= VVS_plusfast  ,
["A  -"]	= VVS_minus  ,
["A --"]	= VVS_minusfast  ,
["PRESS"] 	= VVS_press  ,
["PULL"]        = VVS_pull ,
}


-- ############################################### --
-- ## MCP block Mode 3
-- ############################################### --

-- MCP block buttons and switches
MCP3 = {
["ENABLED"]	= false  ,
["IDENT"] 	= "MCP3"  ,
["MACH."] 	= Autopilot_MACH_button  ,
["LOC ."] 	= Autopilot_LOC_button  ,
["TRK ."] 	= Autopilot_TRK_button  ,
["AP1 ."] 	= Autopilot_AP1_button  ,
["AP2."] 	= Autopilot_AP2_button  ,
["ATHR."] 	= Autopilot_ATHR_button  ,
["EXPD."] 	= Autopilot_EXPD_button  ,
["MTR ."] 	= Autopilot_MTR_button  ,
["APPR."] 	= Autopilot_APPR_button  ,
}


-- MCP SPD knob
SPD3 = {
["A SHOW"]	= SPD_show  ,
["A  +"]	= SPD_plus  ,
["A ++"]	= SPD_plusfast  ,
["A  -"]	= SPD_minus  ,
["A --"]	= SPD_minusfast  ,
["PRESS"] 	= SPD_press  ,
["PULL"]        = SPD_pull ,
}


-- MCP HDG knob
HDG3 = {
["A SHOW"]	= HDG_show  ,
["A  +"]	= HDG_plus  ,
["A ++"]	= HDG_plusfast  ,
["A  -"]	= HDG_minus  ,
["A --"]	= HDG_minusfast  ,
["PRESS"] 	= HDG_press  ,
["PULL"]        = HDG_pull ,
}


-- MCP ALT knob
ALT3 = {
["A SHOW"]	= ALT_show  ,
["A  +"]	= ALT_plus  ,
["A ++"]	= ALT_plusfast  ,
["A  -"]	= ALT_minus  ,
["A --"]	= ALT_minusfast  ,
["PRESS"] 	= ALT_press  ,
["PULL"]        = ALT_pull ,
}


-- MCP VVS knob
VVS3 = {
["A SHOW"]	= VVS_show  ,
["A  +"]	= VVS_plus  ,
["A ++"]	= VVS_plusfast  ,
["A  -"]	= VVS_minus  ,
["A --"]	= VVS_minusfast  ,
["PRESS"] 	= VVS_press  ,
["PULL"]        = VVS_pull ,
}


-- ############################################### --
-- ## USER block Mode 1
-- ############################################### --

-- USER block buttons and switches
USER1 = {
["ENABLED"]	= true  ,
["IDENT"]	= "Lght"  ,
["BTN1."] 	= Lights_PANEL_toggle  ,
["BTN2."] 	= Lights_TAXI_toggle  ,
["BTN3."] 	= Lights_NAV_toggle  ,
["BTN4."] 	= Lights_STROBE_toggle  ,
["BTN5."] 	= Lights_BEACON_toggle  ,
["BTN6."] 	= VRI_EFIS_MODE_toggle  ,
["BTN7."] 	= VRI_MCP_MODE_toggle  ,
["BTN8."] 	= VRI_USER_MODE_toggle  ,
["USR1."]       = empty,
["USR2."]       = empty,
["USR3."]       = empty,
["USR4."]       = empty,
["USR5."]       = empty,
["USR6."]       = empty,
["USR7."]       = empty,
["USR8."]       = empty ,
}

-- ############################################### --
-- ## USER block Mode 2
-- ############################################### --

-- USER block buttons and switches
USER2 = {
["ENABLED"]	= true  ,
["IDENT"]	= "USR2"  ,
["BTN1."] 	= empty  ,
["BTN2."] 	= empty  ,
["BTN3."] 	= empty  ,
["BTN4."] 	= empty  ,
["BTN5."] 	= empty  ,
["BTN6."] 	= VRI_EFIS_MODE_toggle  ,
["BTN7."] 	= VRI_MCP_MODE_toggle  ,
["BTN8."] 	= VRI_USER_MODE_toggle  ,
["USR1."]       = empty,
["USR2."]       = empty,
["USR3."]       = empty,
["USR4."]       = empty,
["USR5."]       = empty,
["USR6."]       = empty,
["USR7."]       = empty,
["USR8."]       = empty ,
}

-- ############################################### --
-- ## USER block Mode 3
-- ############################################### --

-- USER block buttons and switches
USER3 = {
["ENABLED"]	= true  ,
["IDENT"]	= "USR3"  ,
["BTN1."] 	= empty  ,
["BTN2."] 	= empty  ,
["BTN3."] 	= empty  ,
["BTN4."] 	= empty  ,
["BTN5."] 	= empty  ,
["BTN6."] 	= VRI_EFIS_MODE_toggle  ,
["BTN7."] 	= VRI_MCP_MODE_toggle  ,
["BTN8."] 	= VRI_USER_MODE_toggle  ,
["USR1."]       = empty,
["USR2."]       = empty,
["USR3."]       = empty,
["USR4."]       = empty,
["USR5."]       = empty,
["USR6."]       = empty,
["USR7."]       = empty,
["USR8."]       = empty ,
}

-- ############################################### --
-- ## RADIOS block Mode 1
-- ############################################### --

-- RADIOS block buttons and switches
RADIOS = {
["COM ."]	= Default_COM_select  ,
["NAV ."]	= Default_NAV_select  ,
["ADF ."]	= Default_ADF_select  ,
["DME ."]	= Default_DME_select  ,
["TRAN."]	= Default_XPND_select  ,
["TFR ."]	= Default_RADIOS_swap  ,
["STBY."]	= Default_RADIOS_mode  ,
["LAMP."]   = Lights_PANEL_toggle,

["COM1 Select"]	= empty  ,
["COM2 Select"]	= empty  ,
["COM1 Swap"]	= empty  ,
["COM2 Swap"]	= empty  ,
["COMs Mode"]	= Radios_COM_AUDIO_toggle  ,

["NAV1 Select"]	= empty  ,
["NAV2 Select"]	= empty  ,
["NAV1 Swap"]	= empty  ,
["NAV2 Swap"]	= empty  ,
["NAVs Mode"]	= Radios_NAV_AUDIO_toggle  ,

["ADF1 Select"]	= empty  ,
["ADF2 Select"]	= empty  ,
["ADFs Mode"]	= Radios_ADF_AUDIO_toggle  ,

["DME1 Select"]	= empty  ,
["DME2 Select"]	= empty  ,
["DMEs Mode"]	= Radios_DME_AUDIO_toggle  ,

["XPND Select"]	= empty  ,
["XPND Swap"]	= empty  ,
["XPND Mode"]	= Transponder_MODE_toggle  ,
}

DME1 = {
["A  +"]   	= empty  ,
["A ++"]   	= empty  ,
["A  -"]   	= empty  ,
["A --"]   	= empty  ,
["PRESS"]  	= empty  ,
}

FRE1 = {
["A  +"]   	= Default_RADIOS_plus  ,
["A ++"]   	= Default_RADIOS_plusfast  ,
["A  -"]   	= Default_RADIOS_minus  ,
["A --"]   	= Default_RADIOS_minusfast  ,
["PRESS"]  	= Default_RADIOS_press  ,
}
